apiVersion: v1
kind: Secret
metadata:
  name: cred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ2YWxheHkwMTAyMDMuamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogImRtRnNZWGg1TURFd01qQXpPbFpoYkdGNGVVQXdNVEF5TURNPSIKCQl9Cgl9Cn0= 
type: kubernetes.io/dockerconfigjson